name: mainevnap

on:
  schedule:
    - cron: "10 3 * * *"
  workflow_dispatch:

jobs:
  mainevnap:
    runs-on: ubuntu-latest

    steps:
      - name: Repo letöltése
        uses: actions/checkout@v4

      - name: Python beállítása
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Függőségek telepítése
        run: |
          pip install requests beautifulsoup4

      - name: Mainevnap script futtatása
        run: |
          python scripts/mainevnap.py

      - name: JSON commit
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add mainevnap.json
          git commit -m "Mai névnap frissítve" || echo "Nincs változás"
          git push
